name: 'Publish .NET NuGet Package for .net48 and .net8.0'
description: 'Builds and publishes a .NET NuGet package to GitHub Packages'
inputs:
  dotnet-version:
    description: 'Version of .NET SDK to use'
    required: false
    default: '8.0.x'
  gh-packages-token:
    description: 'GitHub Packages token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Install .NET Framework targeting pack
      run: choco install netfx-4.8-devpack -y
      shell: pwsh

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4.1.0
      with:
        versionSpec: '6.4.0'

    - name: Cache NuGet packages        # Try to find if a build cached packages. Maybe the build_check. This saves time
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          nuget-${{ runner.os }}-

    - name: Cache build output      # Try to find if a build cached comiled files. Maybe the build_check. This saves time
      uses: actions/cache@v4
      with:
        path: |
          **/bin
          **/obj
        key: build-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          build-${{ runner.os }}-

    - name: Run GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v4.1.0
      with:
        overrideConfig: |
          workflow=TrunkBased/preview1
          commit-message-incrementing=Enabled
          tag-prefix=v
          increment=Patch

    - name: Show extracted version
      run: echo "Version is ${{ steps.gitversion.outputs.SemVer }}"
      shell: pwsh


    # Ensure that the github-Official-EwE NuGet source is configured. The standard GITHUB_TOKEN is used. It's automatically created by GitHub Actions and is available as 'github.toke'
    # So you don't have to pass it to this action explicitly. (because 'secrets', and subsequently 'secrets.GITHUB_TOKEN' is not accessible in reusable workflows)
    - name: Ensure github-Official-EwE NuGet source
      run: |
        if (dotnet nuget list source | Select-String "github-Official-EwE") {
          dotnet nuget remove source github-Official-EwE
        }
        dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" `
          --name "github-Official-EwE" `
          --username ${{ github.repository_owner }} `
          --password ${{ github.token }} `
          --store-password-in-clear-text
      shell: pwsh



    - name: Restore dependencies
      run: dotnet restore
      shell: pwsh

    - name: Build
      run: dotnet build --configuration Release
      shell: pwsh

    - name: Pack NuGet package
      run: dotnet pack --configuration Release --output ./nuget /p:PackageVersion=${{ steps.gitversion.outputs.SemVer }}
      shell: pwsh

    - name: List NuGet output files
      run: dir ./nuget
      shell: pwsh

    # - name: Add GitHub Packages source
    #   run: dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name github --username ${{ github.actor }} --password ${{ inputs.gh-packages-token }} --store-password-in-clear-text
    #   shell: pwsh

    - name: Publish to GitHub Packages
      run: |
        dotnet nuget push "./nuget/${{ github.event.repository.name }}.${{ steps.gitversion.outputs.SemVer }}.nupkg" --source "github" --api-key ${{ inputs.gh-packages-token }} --skip-duplicate
        dotnet nuget push "./nuget/${{ github.event.repository.name }}.${{ steps.gitversion.outputs.SemVer }}.symbols.nupkg" --source "github" --api-key ${{ inputs.gh-packages-token }} --skip-duplicate
      shell: pwsh
