name: 'Publish .NET NuGet Package for .net48 and .net8.0'
description: 'Builds and publishes a .NET NuGet package to GitHub Packages'
inputs:
  dotnet-version:
    description: 'Version of .NET SDK to use'
    required: false
    default: '8.0.x'
  gh-packages-token:
    description: 'GitHub Packages token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Install .NET Framework targeting pack
      run: choco install netfx-4.8-devpack -y
      shell: pwsh
    - name: Add GitHub Packages source
      run: dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name github --username ${{ github.actor }} --password ${{ inputs.gh-packages-token }} --store-password-in-clear-text
      shell: pwsh
    - name: Restore dependencies
      run: dotnet restore
      shell: pwsh

    - name: Build
      run: dotnet build --configuration Release
      shell: pwsh

    - name: Extract version from tag
      id: get_version
      run: |
        $version = $env:GITHUB_REF -replace 'refs/tags/v', ''
        echo "version=$version" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Pack NuGet package
      run: dotnet pack --configuration Release --output ./nuget /p:PackageVersion=${{ steps.get_version.outputs.version }}
      shell: pwsh

    - name: List NuGet output files
      run: dir ./nuget
      shell: pwsh

    - name: Publish to GitHub Packages
      run: |
        dotnet nuget push "./nuget/${{ github.event.repository.name }}.${{ steps.get_version.outputs.version }}.nupkg" --source "github" --api-key ${{ inputs.gh-packages-token }} --skip-duplicate
        dotnet nuget push "./nuget/${{ github.event.repository.name }}.${{ steps.get_version.outputs.version }}.symbols.nupkg" --source "github" --api-key ${{ inputs.gh-packages-token }} --skip-duplicate
      shell: pwsh
