name: 'Build check for .net8.0' 
description: 'Builds the project. Used to check if there are build errors before checking in'
inputs:
  dotnet-version:
    description: 'Version of .NET to use'
    required: false
    default: '8.0.x'
  solution-file:
    description: 'Solution file to build'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: List Current directory
      run: dir
      shell: pwsh

    - name: Show solution
      run: echo "solution-file is ${{ inputs.solution-file }}"
      shell: pwsh

    - name: Restore dependencies
      run: dotnet restore
      shell: pwsh

    - name: Build solution
      run: dotnet build ${{ inputs.solution-file }} --configuration Release --no-restore
      shell: pwsh